### ISSUE TITLE
Questionário para email dinâmico

### ISSUE THREAD

**Issue by Ca-moes** [Ca-moes/PPIN#3]
Necessário formar um questionário para ser enviado via webmail para obter dados estatísticos sobre a importância da nossa ideia.

## ToDo
- [x] Questionário em Google Forms
- [x] Corpo do e-mail
- [x] Agrupamento e limpeza de dados
